### ISSUE TITLE
MySQL lockdown?

### ISSUE THREAD

**Issue by techopswhiz** [bennetgallein/PaladinsPHP#2]
Seems like a good start, I guess, but I might make my own from scratch anyway.

Why do you force the use of MySQL? I'm using laravel and I'll probably want an eloquent-friendly system.

**Comment by bennetgallein** [comment]
The MySQL is only there to safe the Session for 15 minutes. There are probably tons of other, more better options. I'll maybe change it in the future but for now, I'm quite happy with the solution.

**Comment by bennetgallein** [comment]
markin this as done.
